"""Til sozlamalari"""

LANGUAGES = {
    'uz': {
        'name': "O'zbekcha",
        'start_message': "🏦 <b>Markaziy Bank Valyuta Boti</b>\n\nSalom! Men sizga valyuta kurslari haqida ma'lumot beraman.\n\n📊 <b>Valyuta Statistikasi</b> - Grafiklar va so'nggi kurslar\n🧮 <b>Valyuta Kalkulyatori</b> - Valyuta konvertatsiyasi\n📈 <b>Barcha Valyutalar</b> - Barcha mavjud valyuta kurslari",
        'statistics': "📊 Valyuta Statistikasi",
        'calculator': "🧮 Valyuta Kalkulyatori",
        'all_currencies': "📈 Barcha Valyutalar",
        'loading': "📊 Ma'lumotlar yuklanmoqda...",
        'error': "❌ Ma'lumotlarni olishda xatolik yuz berdi.",
        'cancel': "❌ Bekor qilish",
        'all_currencies_title': "📋 <b>Barcha valyuta kurslari:</b>\n\n",
        'current_rate': "💰 Joriy kurs",
        'date': "📅 Sana",
        'dynamics': "📊 So'nggi 30 kunlik dinamika",
        'conversion_result': "💱 <b>Konvertatsiya Natijasi</b>",
        'rates': "📊 Kurslar",
        'select_from': "🧮 <b>Valyuta Kalkulyatori</b>\n\nQaysi valyutadan aylantirasiz?",
        'select_to': "Tanlandi: <b>{}</b>\n\nQaysi valyutaga aylantirasiz?",
        'enter_amount': "<b>{}</b> → <b>{}</b>\n\nMiqdorni kiriting:",
        'wrong_format': "❌ Noto'g'ri format! Raqam kiriting.",
        'currency_not_found': "❌ Valyuta kursi topilmadi.",
        'cancelled': "❌ Bekor qilindi."
    },
    'ru': {
        'name': "Русский",
        'start_message': "🏦 <b>Бот валют Центрального Банка</b>\n\nПривет! Я предоставлю вам информацию о курсах валют.\n\n📊 <b>Статистика валют</b> - Графики и последние курсы\n🧮 <b>Валютный калькулятор</b> - Конвертация валют\n📈 <b>Все валюты</b> - Все доступные курсы валют",
        'statistics': "📊 Статистика валют",
        'calculator': "🧮 Валютный калькулятор",
        'all_currencies': "📈 Все валюты",
        'loading': "📊 Данные загружаются...",
        'error': "❌ Ошибка при получении данных.",
        'cancel': "❌ Отмена",
        'all_currencies_title': "📋 <b>Все курсы валют:</b>\n\n",
        'current_rate': "💰 Текущий курс",
        'date': "📅 Дата",
        'dynamics': "📊 Динамика за 30 дней",
        'conversion_result': "💱 <b>Результат конвертации</b>",
        'rates': "📊 Курсы",
        'select_from': "🧮 <b>Валютный калькулятор</b>\n\nИз какой валюты конвертировать?",
        'select_to': "Выбрано: <b>{}</b>\n\nВ какую валюту конвертировать?",
        'enter_amount': "<b>{}</b> → <b>{}</b>\n\nВведите сумму:",
        'wrong_format': "❌ Неверный формат! Введите число.",
        'currency_not_found': "❌ Курс валюты не найден.",
        'cancelled': "❌ Отменено."
    },
    'en': {
        'name': "English",
        'start_message': "🏦 <b>Central Bank Currency Bot</b>\n\nHello! I will provide you with currency exchange rate information.\n\n📊 <b>Currency Statistics</b> - Charts and latest rates\n🧮 <b>Currency Calculator</b> - Currency conversion\n📈 <b>All Currencies</b> - All available currency rates",
        'statistics': "📊 Currency Statistics",
        'calculator': "🧮 Currency Calculator",
        'all_currencies': "📈 All Currencies",
        'loading': "📊 Loading data...",
        'error': "❌ Error fetching data.",
        'cancel': "❌ Cancel",
        'all_currencies_title': "📋 <b>All currency rates:</b>\n\n",
        'current_rate': "💰 Current rate",
        'date': "📅 Date",
        'dynamics': "📊 30-day dynamics",
        'conversion_result': "💱 <b>Conversion Result</b>",
        'rates': "📊 Rates",
        'select_from': "🧮 <b>Currency Calculator</b>\n\nWhich currency to convert from?",
        'select_to': "Selected: <b>{}</b>\n\nWhich currency to convert to?",
        'enter_amount': "<b>{}</b> → <b>{}</b>\n\nEnter amount:",
        'wrong_format': "❌ Wrong format! Enter a number.",
        'currency_not_found': "❌ Currency rate not found.",
        'cancelled': "❌ Cancelled."
    }
}